// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"Ratte-Panel-PP/api/models"
)

// GetServerUserListReader is a Reader for the GetServerUserList structure.
type GetServerUserListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServerUserListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServerUserListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/server/user] GetServerUserList", response, response.Code())
	}
}

// NewGetServerUserListOK creates a GetServerUserListOK with default headers values
func NewGetServerUserListOK() *GetServerUserListOK {
	return &GetServerUserListOK{}
}

/*
GetServerUserListOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetServerUserListOK struct {
	Payload *GetServerUserListOKBody
}

// IsSuccess returns true when this get server user list o k response has a 2xx status code
func (o *GetServerUserListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get server user list o k response has a 3xx status code
func (o *GetServerUserListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get server user list o k response has a 4xx status code
func (o *GetServerUserListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get server user list o k response has a 5xx status code
func (o *GetServerUserListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get server user list o k response a status code equal to that given
func (o *GetServerUserListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get server user list o k response
func (o *GetServerUserListOK) Code() int {
	return 200
}

func (o *GetServerUserListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/server/user][%d] getServerUserListOK %s", 200, payload)
}

func (o *GetServerUserListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/server/user][%d] getServerUserListOK %s", 200, payload)
}

func (o *GetServerUserListOK) GetPayload() *GetServerUserListOKBody {
	return o.Payload
}

func (o *GetServerUserListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetServerUserListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetServerUserListOKBody get server user list o k body
swagger:model GetServerUserListOKBody
*/
type GetServerUserListOKBody struct {
	models.Response

	// data
	Data *models.GetServerUserListResponse `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetServerUserListOKBody) UnmarshalJSON(raw []byte) error {
	// GetServerUserListOKBodyAO0
	var getServerUserListOKBodyAO0 models.Response
	if err := swag.ReadJSON(raw, &getServerUserListOKBodyAO0); err != nil {
		return err
	}
	o.Response = getServerUserListOKBodyAO0

	// GetServerUserListOKBodyAO1
	var dataGetServerUserListOKBodyAO1 struct {
		Data *models.GetServerUserListResponse `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetServerUserListOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetServerUserListOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetServerUserListOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getServerUserListOKBodyAO0, err := swag.WriteJSON(o.Response)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getServerUserListOKBodyAO0)
	var dataGetServerUserListOKBodyAO1 struct {
		Data *models.GetServerUserListResponse `json:"data,omitempty"`
	}

	dataGetServerUserListOKBodyAO1.Data = o.Data

	jsonDataGetServerUserListOKBodyAO1, errGetServerUserListOKBodyAO1 := swag.WriteJSON(dataGetServerUserListOKBodyAO1)
	if errGetServerUserListOKBodyAO1 != nil {
		return nil, errGetServerUserListOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetServerUserListOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get server user list o k body
func (o *GetServerUserListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Response
	if err := o.Response.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServerUserListOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getServerUserListOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getServerUserListOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get server user list o k body based on the context it is used
func (o *GetServerUserListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Response
	if err := o.Response.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServerUserListOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getServerUserListOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getServerUserListOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetServerUserListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetServerUserListOKBody) UnmarshalBinary(b []byte) error {
	var res GetServerUserListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
