// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"Ratte-Panel-PP/api/models"
)

// GetServerConfigReader is a Reader for the GetServerConfig structure.
type GetServerConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServerConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServerConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/server/config] GetServerConfig", response, response.Code())
	}
}

// NewGetServerConfigOK creates a GetServerConfigOK with default headers values
func NewGetServerConfigOK() *GetServerConfigOK {
	return &GetServerConfigOK{}
}

/*
GetServerConfigOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetServerConfigOK struct {
	Payload *GetServerConfigOKBody
}

// IsSuccess returns true when this get server config o k response has a 2xx status code
func (o *GetServerConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get server config o k response has a 3xx status code
func (o *GetServerConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get server config o k response has a 4xx status code
func (o *GetServerConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get server config o k response has a 5xx status code
func (o *GetServerConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get server config o k response a status code equal to that given
func (o *GetServerConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get server config o k response
func (o *GetServerConfigOK) Code() int {
	return 200
}

func (o *GetServerConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/server/config][%d] getServerConfigOK %s", 200, payload)
}

func (o *GetServerConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/server/config][%d] getServerConfigOK %s", 200, payload)
}

func (o *GetServerConfigOK) GetPayload() *GetServerConfigOKBody {
	return o.Payload
}

func (o *GetServerConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetServerConfigOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetServerConfigOKBody get server config o k body
swagger:model GetServerConfigOKBody
*/
type GetServerConfigOKBody struct {
	models.Response

	// data
	Data *models.GetServerConfigResponse `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetServerConfigOKBody) UnmarshalJSON(raw []byte) error {
	// GetServerConfigOKBodyAO0
	var getServerConfigOKBodyAO0 models.Response
	if err := swag.ReadJSON(raw, &getServerConfigOKBodyAO0); err != nil {
		return err
	}
	o.Response = getServerConfigOKBodyAO0

	// GetServerConfigOKBodyAO1
	var dataGetServerConfigOKBodyAO1 struct {
		Data *models.GetServerConfigResponse `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetServerConfigOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetServerConfigOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetServerConfigOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getServerConfigOKBodyAO0, err := swag.WriteJSON(o.Response)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getServerConfigOKBodyAO0)
	var dataGetServerConfigOKBodyAO1 struct {
		Data *models.GetServerConfigResponse `json:"data,omitempty"`
	}

	dataGetServerConfigOKBodyAO1.Data = o.Data

	jsonDataGetServerConfigOKBodyAO1, errGetServerConfigOKBodyAO1 := swag.WriteJSON(dataGetServerConfigOKBodyAO1)
	if errGetServerConfigOKBodyAO1 != nil {
		return nil, errGetServerConfigOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetServerConfigOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get server config o k body
func (o *GetServerConfigOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Response
	if err := o.Response.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServerConfigOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getServerConfigOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getServerConfigOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get server config o k body based on the context it is used
func (o *GetServerConfigOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Response
	if err := o.Response.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServerConfigOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getServerConfigOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getServerConfigOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetServerConfigOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetServerConfigOKBody) UnmarshalBinary(b []byte) error {
	var res GetServerConfigOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
