// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"Ratte-Panel-PP/api/models"
)

// NewPushOnlineUsersParams creates a new PushOnlineUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPushOnlineUsersParams() *PushOnlineUsersParams {
	return &PushOnlineUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPushOnlineUsersParamsWithTimeout creates a new PushOnlineUsersParams object
// with the ability to set a timeout on a request.
func NewPushOnlineUsersParamsWithTimeout(timeout time.Duration) *PushOnlineUsersParams {
	return &PushOnlineUsersParams{
		timeout: timeout,
	}
}

// NewPushOnlineUsersParamsWithContext creates a new PushOnlineUsersParams object
// with the ability to set a context for a request.
func NewPushOnlineUsersParamsWithContext(ctx context.Context) *PushOnlineUsersParams {
	return &PushOnlineUsersParams{
		Context: ctx,
	}
}

// NewPushOnlineUsersParamsWithHTTPClient creates a new PushOnlineUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPushOnlineUsersParamsWithHTTPClient(client *http.Client) *PushOnlineUsersParams {
	return &PushOnlineUsersParams{
		HTTPClient: client,
	}
}

/*
PushOnlineUsersParams contains all the parameters to send to the API endpoint

	for the push online users operation.

	Typically these are written to a http.Request.
*/
type PushOnlineUsersParams struct {

	// Body.
	Body *models.OnlineUsersRequest

	// Protocol.
	Protocol string

	// SecretKey.
	SecretKey string

	// ServerID.
	//
	// Format: int64
	ServerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the push online users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PushOnlineUsersParams) WithDefaults() *PushOnlineUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the push online users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PushOnlineUsersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the push online users params
func (o *PushOnlineUsersParams) WithTimeout(timeout time.Duration) *PushOnlineUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the push online users params
func (o *PushOnlineUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the push online users params
func (o *PushOnlineUsersParams) WithContext(ctx context.Context) *PushOnlineUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the push online users params
func (o *PushOnlineUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the push online users params
func (o *PushOnlineUsersParams) WithHTTPClient(client *http.Client) *PushOnlineUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the push online users params
func (o *PushOnlineUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the push online users params
func (o *PushOnlineUsersParams) WithBody(body *models.OnlineUsersRequest) *PushOnlineUsersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the push online users params
func (o *PushOnlineUsersParams) SetBody(body *models.OnlineUsersRequest) {
	o.Body = body
}

// WithProtocol adds the protocol to the push online users params
func (o *PushOnlineUsersParams) WithProtocol(protocol string) *PushOnlineUsersParams {
	o.SetProtocol(protocol)
	return o
}

// SetProtocol adds the protocol to the push online users params
func (o *PushOnlineUsersParams) SetProtocol(protocol string) {
	o.Protocol = protocol
}

// WithSecretKey adds the secretKey to the push online users params
func (o *PushOnlineUsersParams) WithSecretKey(secretKey string) *PushOnlineUsersParams {
	o.SetSecretKey(secretKey)
	return o
}

// SetSecretKey adds the secretKey to the push online users params
func (o *PushOnlineUsersParams) SetSecretKey(secretKey string) {
	o.SecretKey = secretKey
}

// WithServerID adds the serverID to the push online users params
func (o *PushOnlineUsersParams) WithServerID(serverID int64) *PushOnlineUsersParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the push online users params
func (o *PushOnlineUsersParams) SetServerID(serverID int64) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *PushOnlineUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// query param protocol
	qrProtocol := o.Protocol
	qProtocol := qrProtocol
	if qProtocol != "" {

		if err := r.SetQueryParam("protocol", qProtocol); err != nil {
			return err
		}
	}

	// query param secret_key
	qrSecretKey := o.SecretKey
	qSecretKey := qrSecretKey
	if qSecretKey != "" {

		if err := r.SetQueryParam("secret_key", qSecretKey); err != nil {
			return err
		}
	}

	// query param server_id
	qrServerID := o.ServerID
	qServerID := swag.FormatInt64(qrServerID)
	if qServerID != "" {

		if err := r.SetQueryParam("server_id", qServerID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
