// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"Ratte-Panel-PP/api/models"
)

// PushOnlineUsersReader is a Reader for the PushOnlineUsers structure.
type PushOnlineUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PushOnlineUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPushOnlineUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/server/online] PushOnlineUsers", response, response.Code())
	}
}

// NewPushOnlineUsersOK creates a PushOnlineUsersOK with default headers values
func NewPushOnlineUsersOK() *PushOnlineUsersOK {
	return &PushOnlineUsersOK{}
}

/*
PushOnlineUsersOK describes a response with status code 200, with default header values.

A successful response.
*/
type PushOnlineUsersOK struct {
	Payload *PushOnlineUsersOKBody
}

// IsSuccess returns true when this push online users o k response has a 2xx status code
func (o *PushOnlineUsersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this push online users o k response has a 3xx status code
func (o *PushOnlineUsersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this push online users o k response has a 4xx status code
func (o *PushOnlineUsersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this push online users o k response has a 5xx status code
func (o *PushOnlineUsersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this push online users o k response a status code equal to that given
func (o *PushOnlineUsersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the push online users o k response
func (o *PushOnlineUsersOK) Code() int {
	return 200
}

func (o *PushOnlineUsersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/server/online][%d] pushOnlineUsersOK %s", 200, payload)
}

func (o *PushOnlineUsersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/server/online][%d] pushOnlineUsersOK %s", 200, payload)
}

func (o *PushOnlineUsersOK) GetPayload() *PushOnlineUsersOKBody {
	return o.Payload
}

func (o *PushOnlineUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PushOnlineUsersOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PushOnlineUsersOKBody push online users o k body
swagger:model PushOnlineUsersOKBody
*/
type PushOnlineUsersOKBody struct {
	models.Response

	// data
	Data interface{} `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PushOnlineUsersOKBody) UnmarshalJSON(raw []byte) error {
	// PushOnlineUsersOKBodyAO0
	var pushOnlineUsersOKBodyAO0 models.Response
	if err := swag.ReadJSON(raw, &pushOnlineUsersOKBodyAO0); err != nil {
		return err
	}
	o.Response = pushOnlineUsersOKBodyAO0

	// PushOnlineUsersOKBodyAO1
	var dataPushOnlineUsersOKBodyAO1 struct {
		Data interface{} `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPushOnlineUsersOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataPushOnlineUsersOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PushOnlineUsersOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	pushOnlineUsersOKBodyAO0, err := swag.WriteJSON(o.Response)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, pushOnlineUsersOKBodyAO0)
	var dataPushOnlineUsersOKBodyAO1 struct {
		Data interface{} `json:"data,omitempty"`
	}

	dataPushOnlineUsersOKBodyAO1.Data = o.Data

	jsonDataPushOnlineUsersOKBodyAO1, errPushOnlineUsersOKBodyAO1 := swag.WriteJSON(dataPushOnlineUsersOKBodyAO1)
	if errPushOnlineUsersOKBodyAO1 != nil {
		return nil, errPushOnlineUsersOKBodyAO1
	}
	_parts = append(_parts, jsonDataPushOnlineUsersOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this push online users o k body
func (o *PushOnlineUsersOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Response
	if err := o.Response.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this push online users o k body based on the context it is used
func (o *PushOnlineUsersOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Response
	if err := o.Response.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *PushOnlineUsersOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PushOnlineUsersOKBody) UnmarshalBinary(b []byte) error {
	var res PushOnlineUsersOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
