// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"Ratte-Panel-PP/api/models"
)

// NewServerPushUserTrafficParams creates a new ServerPushUserTrafficParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServerPushUserTrafficParams() *ServerPushUserTrafficParams {
	return &ServerPushUserTrafficParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServerPushUserTrafficParamsWithTimeout creates a new ServerPushUserTrafficParams object
// with the ability to set a timeout on a request.
func NewServerPushUserTrafficParamsWithTimeout(timeout time.Duration) *ServerPushUserTrafficParams {
	return &ServerPushUserTrafficParams{
		timeout: timeout,
	}
}

// NewServerPushUserTrafficParamsWithContext creates a new ServerPushUserTrafficParams object
// with the ability to set a context for a request.
func NewServerPushUserTrafficParamsWithContext(ctx context.Context) *ServerPushUserTrafficParams {
	return &ServerPushUserTrafficParams{
		Context: ctx,
	}
}

// NewServerPushUserTrafficParamsWithHTTPClient creates a new ServerPushUserTrafficParams object
// with the ability to set a custom HTTPClient for a request.
func NewServerPushUserTrafficParamsWithHTTPClient(client *http.Client) *ServerPushUserTrafficParams {
	return &ServerPushUserTrafficParams{
		HTTPClient: client,
	}
}

/*
ServerPushUserTrafficParams contains all the parameters to send to the API endpoint

	for the server push user traffic operation.

	Typically these are written to a http.Request.
*/
type ServerPushUserTrafficParams struct {

	// Body.
	Body *models.ServerPushUserTrafficRequest

	// Protocol.
	Protocol string

	// SecretKey.
	SecretKey string

	// ServerID.
	//
	// Format: int64
	ServerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the server push user traffic params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerPushUserTrafficParams) WithDefaults() *ServerPushUserTrafficParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the server push user traffic params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServerPushUserTrafficParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the server push user traffic params
func (o *ServerPushUserTrafficParams) WithTimeout(timeout time.Duration) *ServerPushUserTrafficParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the server push user traffic params
func (o *ServerPushUserTrafficParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the server push user traffic params
func (o *ServerPushUserTrafficParams) WithContext(ctx context.Context) *ServerPushUserTrafficParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the server push user traffic params
func (o *ServerPushUserTrafficParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the server push user traffic params
func (o *ServerPushUserTrafficParams) WithHTTPClient(client *http.Client) *ServerPushUserTrafficParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the server push user traffic params
func (o *ServerPushUserTrafficParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the server push user traffic params
func (o *ServerPushUserTrafficParams) WithBody(body *models.ServerPushUserTrafficRequest) *ServerPushUserTrafficParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the server push user traffic params
func (o *ServerPushUserTrafficParams) SetBody(body *models.ServerPushUserTrafficRequest) {
	o.Body = body
}

// WithProtocol adds the protocol to the server push user traffic params
func (o *ServerPushUserTrafficParams) WithProtocol(protocol string) *ServerPushUserTrafficParams {
	o.SetProtocol(protocol)
	return o
}

// SetProtocol adds the protocol to the server push user traffic params
func (o *ServerPushUserTrafficParams) SetProtocol(protocol string) {
	o.Protocol = protocol
}

// WithSecretKey adds the secretKey to the server push user traffic params
func (o *ServerPushUserTrafficParams) WithSecretKey(secretKey string) *ServerPushUserTrafficParams {
	o.SetSecretKey(secretKey)
	return o
}

// SetSecretKey adds the secretKey to the server push user traffic params
func (o *ServerPushUserTrafficParams) SetSecretKey(secretKey string) {
	o.SecretKey = secretKey
}

// WithServerID adds the serverID to the server push user traffic params
func (o *ServerPushUserTrafficParams) WithServerID(serverID int64) *ServerPushUserTrafficParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the server push user traffic params
func (o *ServerPushUserTrafficParams) SetServerID(serverID int64) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *ServerPushUserTrafficParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// query param protocol
	qrProtocol := o.Protocol
	qProtocol := qrProtocol
	if qProtocol != "" {

		if err := r.SetQueryParam("protocol", qProtocol); err != nil {
			return err
		}
	}

	// query param secret_key
	qrSecretKey := o.SecretKey
	qSecretKey := qrSecretKey
	if qSecretKey != "" {

		if err := r.SetQueryParam("secret_key", qSecretKey); err != nil {
			return err
		}
	}

	// query param server_id
	qrServerID := o.ServerID
	qServerID := swag.FormatInt64(qrServerID)
	if qServerID != "" {

		if err := r.SetQueryParam("server_id", qServerID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
