// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"Ratte-Panel-PP/api/models"
)

// ServerPushUserTrafficReader is a Reader for the ServerPushUserTraffic structure.
type ServerPushUserTrafficReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServerPushUserTrafficReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServerPushUserTrafficOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/server/push] ServerPushUserTraffic", response, response.Code())
	}
}

// NewServerPushUserTrafficOK creates a ServerPushUserTrafficOK with default headers values
func NewServerPushUserTrafficOK() *ServerPushUserTrafficOK {
	return &ServerPushUserTrafficOK{}
}

/*
ServerPushUserTrafficOK describes a response with status code 200, with default header values.

A successful response.
*/
type ServerPushUserTrafficOK struct {
	Payload *ServerPushUserTrafficOKBody
}

// IsSuccess returns true when this server push user traffic o k response has a 2xx status code
func (o *ServerPushUserTrafficOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this server push user traffic o k response has a 3xx status code
func (o *ServerPushUserTrafficOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this server push user traffic o k response has a 4xx status code
func (o *ServerPushUserTrafficOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this server push user traffic o k response has a 5xx status code
func (o *ServerPushUserTrafficOK) IsServerError() bool {
	return false
}

// IsCode returns true when this server push user traffic o k response a status code equal to that given
func (o *ServerPushUserTrafficOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the server push user traffic o k response
func (o *ServerPushUserTrafficOK) Code() int {
	return 200
}

func (o *ServerPushUserTrafficOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/server/push][%d] serverPushUserTrafficOK %s", 200, payload)
}

func (o *ServerPushUserTrafficOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/server/push][%d] serverPushUserTrafficOK %s", 200, payload)
}

func (o *ServerPushUserTrafficOK) GetPayload() *ServerPushUserTrafficOKBody {
	return o.Payload
}

func (o *ServerPushUserTrafficOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServerPushUserTrafficOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
ServerPushUserTrafficOKBody server push user traffic o k body
swagger:model ServerPushUserTrafficOKBody
*/
type ServerPushUserTrafficOKBody struct {
	models.Response

	// data
	Data interface{} `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *ServerPushUserTrafficOKBody) UnmarshalJSON(raw []byte) error {
	// ServerPushUserTrafficOKBodyAO0
	var serverPushUserTrafficOKBodyAO0 models.Response
	if err := swag.ReadJSON(raw, &serverPushUserTrafficOKBodyAO0); err != nil {
		return err
	}
	o.Response = serverPushUserTrafficOKBodyAO0

	// ServerPushUserTrafficOKBodyAO1
	var dataServerPushUserTrafficOKBodyAO1 struct {
		Data interface{} `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataServerPushUserTrafficOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataServerPushUserTrafficOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o ServerPushUserTrafficOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	serverPushUserTrafficOKBodyAO0, err := swag.WriteJSON(o.Response)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, serverPushUserTrafficOKBodyAO0)
	var dataServerPushUserTrafficOKBodyAO1 struct {
		Data interface{} `json:"data,omitempty"`
	}

	dataServerPushUserTrafficOKBodyAO1.Data = o.Data

	jsonDataServerPushUserTrafficOKBodyAO1, errServerPushUserTrafficOKBodyAO1 := swag.WriteJSON(dataServerPushUserTrafficOKBodyAO1)
	if errServerPushUserTrafficOKBodyAO1 != nil {
		return nil, errServerPushUserTrafficOKBodyAO1
	}
	_parts = append(_parts, jsonDataServerPushUserTrafficOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this server push user traffic o k body
func (o *ServerPushUserTrafficOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Response
	if err := o.Response.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this server push user traffic o k body based on the context it is used
func (o *ServerPushUserTrafficOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Response
	if err := o.Response.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *ServerPushUserTrafficOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServerPushUserTrafficOKBody) UnmarshalBinary(b []byte) error {
	var res ServerPushUserTrafficOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
