// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CheckoutOrderResponse CheckoutOrderResponse
//
// swagger:model CheckoutOrderResponse
type CheckoutOrderResponse struct {

	// checkout url
	CheckoutURL string `json:"checkout_url,omitempty"`

	// stripe
	Stripe *StripePayment `json:"stripe,omitempty"`

	// type
	// Required: true
	Type *string `json:"type"`
}

// Validate validates this checkout order response
func (m *CheckoutOrderResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStripe(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CheckoutOrderResponse) validateStripe(formats strfmt.Registry) error {
	if swag.IsZero(m.Stripe) { // not required
		return nil
	}

	if m.Stripe != nil {
		if err := m.Stripe.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stripe")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stripe")
			}
			return err
		}
	}

	return nil
}

func (m *CheckoutOrderResponse) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this checkout order response based on the context it is used
func (m *CheckoutOrderResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStripe(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CheckoutOrderResponse) contextValidateStripe(ctx context.Context, formats strfmt.Registry) error {

	if m.Stripe != nil {

		if swag.IsZero(m.Stripe) { // not required
			return nil
		}

		if err := m.Stripe.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stripe")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stripe")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CheckoutOrderResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckoutOrderResponse) UnmarshalBinary(b []byte) error {
	var res CheckoutOrderResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
