// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetServerConfigRequest GetServerConfigRequest
//
// swagger:model GetServerConfigRequest
type GetServerConfigRequest struct {

	// protocol
	Protocol string `json:"protocol,omitempty"`

	// secret key
	SecretKey string `json:"secret_key,omitempty"`

	// server id
	ServerID int64 `json:"server_id,omitempty"`
}

// Validate validates this get server config request
func (m *GetServerConfigRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get server config request based on context it is used
func (m *GetServerConfigRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetServerConfigRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetServerConfigRequest) UnmarshalBinary(b []byte) error {
	var res GetServerConfigRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
