// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MobileAuthenticateConfig MobileAuthenticateConfig
//
// swagger:model MobileAuthenticateConfig
type MobileAuthenticateConfig struct {

	// enable
	// Required: true
	Enable bool `json:"enable"`

	// enable whitelist
	// Required: true
	EnableWhitelist bool `json:"enable_whitelist"`

	// whitelist
	// Required: true
	Whitelist []string `json:"whitelist"`
}

// Validate validates this mobile authenticate config
func (m *MobileAuthenticateConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnable(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnableWhitelist(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWhitelist(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MobileAuthenticateConfig) validateEnable(formats strfmt.Registry) error {

	if err := validate.Required("enable", "body", bool(m.Enable)); err != nil {
		return err
	}

	return nil
}

func (m *MobileAuthenticateConfig) validateEnableWhitelist(formats strfmt.Registry) error {

	if err := validate.Required("enable_whitelist", "body", bool(m.EnableWhitelist)); err != nil {
		return err
	}

	return nil
}

func (m *MobileAuthenticateConfig) validateWhitelist(formats strfmt.Registry) error {

	if err := validate.Required("whitelist", "body", m.Whitelist); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this mobile authenticate config based on context it is used
func (m *MobileAuthenticateConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MobileAuthenticateConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MobileAuthenticateConfig) UnmarshalBinary(b []byte) error {
	var res MobileAuthenticateConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
