// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderDetail OrderDetail
//
// swagger:model OrderDetail
type OrderDetail struct {

	// amount
	// Required: true
	Amount *int64 `json:"amount"`

	// commission
	Commission int64 `json:"commission,omitempty"`

	// coupon
	// Required: true
	Coupon *string `json:"coupon"`

	// coupon discount
	// Required: true
	CouponDiscount *int64 `json:"coupon_discount"`

	// created at
	// Required: true
	CreatedAt *int64 `json:"created_at"`

	// discount
	// Required: true
	Discount *int64 `json:"discount"`

	// fee amount
	// Required: true
	FeeAmount *int64 `json:"fee_amount"`

	// gift amount
	// Required: true
	GiftAmount *int64 `json:"gift_amount"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// method
	// Required: true
	Method *string `json:"method"`

	// order no
	// Required: true
	OrderNo *string `json:"order_no"`

	// payment
	// Required: true
	Payment *PaymentMethod `json:"payment"`

	// price
	// Required: true
	Price *int64 `json:"price"`

	// quantity
	// Required: true
	Quantity *int64 `json:"quantity"`

	// status
	// Required: true
	Status *uint8 `json:"status"`

	// subscribe
	// Required: true
	Subscribe *Subscribe `json:"subscribe"`

	// subscribe id
	// Required: true
	SubscribeID *int64 `json:"subscribe_id"`

	// trade no
	// Required: true
	TradeNo *string `json:"trade_no"`

	// type
	// Required: true
	Type *uint8 `json:"type"`

	// updated at
	// Required: true
	UpdatedAt *int64 `json:"updated_at"`

	// user id
	// Required: true
	UserID *int64 `json:"user_id"`
}

// Validate validates this order detail
func (m *OrderDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCoupon(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCouponDiscount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiscount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFeeAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGiftAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderNo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePayment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubscribe(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubscribeID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTradeNo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderDetail) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateCoupon(formats strfmt.Registry) error {

	if err := validate.Required("coupon", "body", m.Coupon); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateCouponDiscount(formats strfmt.Registry) error {

	if err := validate.Required("coupon_discount", "body", m.CouponDiscount); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateDiscount(formats strfmt.Registry) error {

	if err := validate.Required("discount", "body", m.Discount); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateFeeAmount(formats strfmt.Registry) error {

	if err := validate.Required("fee_amount", "body", m.FeeAmount); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateGiftAmount(formats strfmt.Registry) error {

	if err := validate.Required("gift_amount", "body", m.GiftAmount); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateMethod(formats strfmt.Registry) error {

	if err := validate.Required("method", "body", m.Method); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateOrderNo(formats strfmt.Registry) error {

	if err := validate.Required("order_no", "body", m.OrderNo); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validatePayment(formats strfmt.Registry) error {

	if err := validate.Required("payment", "body", m.Payment); err != nil {
		return err
	}

	if m.Payment != nil {
		if err := m.Payment.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("payment")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("payment")
			}
			return err
		}
	}

	return nil
}

func (m *OrderDetail) validatePrice(formats strfmt.Registry) error {

	if err := validate.Required("price", "body", m.Price); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateSubscribe(formats strfmt.Registry) error {

	if err := validate.Required("subscribe", "body", m.Subscribe); err != nil {
		return err
	}

	if m.Subscribe != nil {
		if err := m.Subscribe.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("subscribe")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("subscribe")
			}
			return err
		}
	}

	return nil
}

func (m *OrderDetail) validateSubscribeID(formats strfmt.Registry) error {

	if err := validate.Required("subscribe_id", "body", m.SubscribeID); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateTradeNo(formats strfmt.Registry) error {

	if err := validate.Required("trade_no", "body", m.TradeNo); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("updated_at", "body", m.UpdatedAt); err != nil {
		return err
	}

	return nil
}

func (m *OrderDetail) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this order detail based on the context it is used
func (m *OrderDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePayment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSubscribe(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderDetail) contextValidatePayment(ctx context.Context, formats strfmt.Registry) error {

	if m.Payment != nil {

		if err := m.Payment.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("payment")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("payment")
			}
			return err
		}
	}

	return nil
}

func (m *OrderDetail) contextValidateSubscribe(ctx context.Context, formats strfmt.Registry) error {

	if m.Subscribe != nil {

		if err := m.Subscribe.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("subscribe")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("subscribe")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderDetail) UnmarshalBinary(b []byte) error {
	var res OrderDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
