// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlatformInfo PlatformInfo
//
// swagger:model PlatformInfo
type PlatformInfo struct {

	// platform
	// Required: true
	Platform *string `json:"platform"`

	// platform field description
	// Required: true
	PlatformFieldDescription interface{} `json:"platform_field_description"`

	// platform url
	// Required: true
	PlatformURL *string `json:"platform_url"`
}

// Validate validates this platform info
func (m *PlatformInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlatform(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlatformFieldDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlatformURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlatformInfo) validatePlatform(formats strfmt.Registry) error {

	if err := validate.Required("platform", "body", m.Platform); err != nil {
		return err
	}

	return nil
}

func (m *PlatformInfo) validatePlatformFieldDescription(formats strfmt.Registry) error {

	if m.PlatformFieldDescription == nil {
		return errors.Required("platform_field_description", "body", nil)
	}

	return nil
}

func (m *PlatformInfo) validatePlatformURL(formats strfmt.Registry) error {

	if err := validate.Required("platform_url", "body", m.PlatformURL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this platform info based on context it is used
func (m *PlatformInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlatformInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlatformInfo) UnmarshalBinary(b []byte) error {
	var res PlatformInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
