// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PrivacyPolicyConfig PrivacyPolicyConfig
//
// swagger:model PrivacyPolicyConfig
type PrivacyPolicyConfig struct {

	// privacy policy
	// Required: true
	PrivacyPolicy *string `json:"privacy_policy"`
}

// Validate validates this privacy policy config
func (m *PrivacyPolicyConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrivacyPolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PrivacyPolicyConfig) validatePrivacyPolicy(formats strfmt.Registry) error {

	if err := validate.Required("privacy_policy", "body", m.PrivacyPolicy); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this privacy policy config based on context it is used
func (m *PrivacyPolicyConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PrivacyPolicyConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PrivacyPolicyConfig) UnmarshalBinary(b []byte) error {
	var res PrivacyPolicyConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
