// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PubilcVerifyCodeConfig PubilcVerifyCodeConfig
//
// swagger:model PubilcVerifyCodeConfig
type PubilcVerifyCodeConfig struct {

	// verify code interval
	// Required: true
	VerifyCodeInterval *int64 `json:"verify_code_interval"`
}

// Validate validates this pubilc verify code config
func (m *PubilcVerifyCodeConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVerifyCodeInterval(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PubilcVerifyCodeConfig) validateVerifyCodeInterval(formats strfmt.Registry) error {

	if err := validate.Required("verify_code_interval", "body", m.VerifyCodeInterval); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this pubilc verify code config based on context it is used
func (m *PubilcVerifyCodeConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PubilcVerifyCodeConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PubilcVerifyCodeConfig) UnmarshalBinary(b []byte) error {
	var res PubilcVerifyCodeConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
