// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PurchaseOrderRequest PurchaseOrderRequest
//
// swagger:model PurchaseOrderRequest
type PurchaseOrderRequest struct {

	// coupon
	Coupon string `json:"coupon,omitempty"`

	// payment
	Payment int64 `json:"payment,omitempty"`

	// quantity
	// Required: true
	Quantity *int64 `json:"quantity"`

	// subscribe id
	// Required: true
	SubscribeID *int64 `json:"subscribe_id"`
}

// Validate validates this purchase order request
func (m *PurchaseOrderRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubscribeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PurchaseOrderRequest) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

func (m *PurchaseOrderRequest) validateSubscribeID(formats strfmt.Registry) error {

	if err := validate.Required("subscribe_id", "body", m.SubscribeID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this purchase order request based on context it is used
func (m *PurchaseOrderRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PurchaseOrderRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PurchaseOrderRequest) UnmarshalBinary(b []byte) error {
	var res PurchaseOrderRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
