// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// QueryAnnouncementResponse QueryAnnouncementResponse
//
// swagger:model QueryAnnouncementResponse
type QueryAnnouncementResponse struct {

	// announcements
	// Required: true
	Announcements []*Announcement `json:"announcements"`

	// total
	// Required: true
	Total *int64 `json:"total"`
}

// Validate validates this query announcement response
func (m *QueryAnnouncementResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnnouncements(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotal(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryAnnouncementResponse) validateAnnouncements(formats strfmt.Registry) error {

	if err := validate.Required("announcements", "body", m.Announcements); err != nil {
		return err
	}

	for i := 0; i < len(m.Announcements); i++ {
		if swag.IsZero(m.Announcements[i]) { // not required
			continue
		}

		if m.Announcements[i] != nil {
			if err := m.Announcements[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("announcements" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("announcements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *QueryAnnouncementResponse) validateTotal(formats strfmt.Registry) error {

	if err := validate.Required("total", "body", m.Total); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this query announcement response based on the context it is used
func (m *QueryAnnouncementResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAnnouncements(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryAnnouncementResponse) contextValidateAnnouncements(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Announcements); i++ {

		if m.Announcements[i] != nil {

			if swag.IsZero(m.Announcements[i]) { // not required
				return nil
			}

			if err := m.Announcements[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("announcements" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("announcements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *QueryAnnouncementResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryAnnouncementResponse) UnmarshalBinary(b []byte) error {
	var res QueryAnnouncementResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
