// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// QueryAnnouncementRequest QueryAnnouncementRequest
//
// swagger:model QueryAnnouncementRequest
type QueryAnnouncementRequest struct {

	// page
	// Required: true
	Page *int32 `json:"page"`

	// pinned
	// Required: true
	Pinned bool `json:"pinned"`

	// popup
	// Required: true
	Popup bool `json:"popup"`

	// size
	// Required: true
	Size *int32 `json:"size"`
}

// Validate validates this query announcement request
func (m *QueryAnnouncementRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePinned(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePopup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryAnnouncementRequest) validatePage(formats strfmt.Registry) error {

	if err := validate.Required("page", "body", m.Page); err != nil {
		return err
	}

	return nil
}

func (m *QueryAnnouncementRequest) validatePinned(formats strfmt.Registry) error {

	if err := validate.Required("pinned", "body", bool(m.Pinned)); err != nil {
		return err
	}

	return nil
}

func (m *QueryAnnouncementRequest) validatePopup(formats strfmt.Registry) error {

	if err := validate.Required("popup", "body", bool(m.Popup)); err != nil {
		return err
	}

	return nil
}

func (m *QueryAnnouncementRequest) validateSize(formats strfmt.Registry) error {

	if err := validate.Required("size", "body", m.Size); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this query announcement request based on context it is used
func (m *QueryAnnouncementRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryAnnouncementRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryAnnouncementRequest) UnmarshalBinary(b []byte) error {
	var res QueryAnnouncementRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
