// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// QueryUserAffiliateCountResponse QueryUserAffiliateCountResponse
//
// swagger:model QueryUserAffiliateCountResponse
type QueryUserAffiliateCountResponse struct {

	// registers
	// Required: true
	Registers *int64 `json:"registers"`

	// total commission
	// Required: true
	TotalCommission *int64 `json:"total_commission"`
}

// Validate validates this query user affiliate count response
func (m *QueryUserAffiliateCountResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegisters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalCommission(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *QueryUserAffiliateCountResponse) validateRegisters(formats strfmt.Registry) error {

	if err := validate.Required("registers", "body", m.Registers); err != nil {
		return err
	}

	return nil
}

func (m *QueryUserAffiliateCountResponse) validateTotalCommission(formats strfmt.Registry) error {

	if err := validate.Required("total_commission", "body", m.TotalCommission); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this query user affiliate count response based on context it is used
func (m *QueryUserAffiliateCountResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QueryUserAffiliateCountResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QueryUserAffiliateCountResponse) UnmarshalBinary(b []byte) error {
	var res QueryUserAffiliateCountResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
