// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RegisterConfig RegisterConfig
//
// swagger:model RegisterConfig
type RegisterConfig struct {

	// enable ip register limit
	// Required: true
	EnableIPRegisterLimit bool `json:"enable_ip_register_limit"`

	// enable trial
	// Required: true
	EnableTrial bool `json:"enable_trial"`

	// ip register limit
	// Required: true
	IPRegisterLimit *int64 `json:"ip_register_limit"`

	// ip register limit duration
	// Required: true
	IPRegisterLimitDuration *int64 `json:"ip_register_limit_duration"`

	// stop register
	// Required: true
	StopRegister bool `json:"stop_register"`

	// trial subscribe
	// Required: true
	TrialSubscribe *int64 `json:"trial_subscribe"`

	// trial time
	// Required: true
	TrialTime *int64 `json:"trial_time"`

	// trial time unit
	// Required: true
	TrialTimeUnit *string `json:"trial_time_unit"`
}

// Validate validates this register config
func (m *RegisterConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnableIPRegisterLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnableTrial(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIPRegisterLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIPRegisterLimitDuration(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStopRegister(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrialSubscribe(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrialTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrialTimeUnit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegisterConfig) validateEnableIPRegisterLimit(formats strfmt.Registry) error {

	if err := validate.Required("enable_ip_register_limit", "body", bool(m.EnableIPRegisterLimit)); err != nil {
		return err
	}

	return nil
}

func (m *RegisterConfig) validateEnableTrial(formats strfmt.Registry) error {

	if err := validate.Required("enable_trial", "body", bool(m.EnableTrial)); err != nil {
		return err
	}

	return nil
}

func (m *RegisterConfig) validateIPRegisterLimit(formats strfmt.Registry) error {

	if err := validate.Required("ip_register_limit", "body", m.IPRegisterLimit); err != nil {
		return err
	}

	return nil
}

func (m *RegisterConfig) validateIPRegisterLimitDuration(formats strfmt.Registry) error {

	if err := validate.Required("ip_register_limit_duration", "body", m.IPRegisterLimitDuration); err != nil {
		return err
	}

	return nil
}

func (m *RegisterConfig) validateStopRegister(formats strfmt.Registry) error {

	if err := validate.Required("stop_register", "body", bool(m.StopRegister)); err != nil {
		return err
	}

	return nil
}

func (m *RegisterConfig) validateTrialSubscribe(formats strfmt.Registry) error {

	if err := validate.Required("trial_subscribe", "body", m.TrialSubscribe); err != nil {
		return err
	}

	return nil
}

func (m *RegisterConfig) validateTrialTime(formats strfmt.Registry) error {

	if err := validate.Required("trial_time", "body", m.TrialTime); err != nil {
		return err
	}

	return nil
}

func (m *RegisterConfig) validateTrialTimeUnit(formats strfmt.Registry) error {

	if err := validate.Required("trial_time_unit", "body", m.TrialTimeUnit); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this register config based on context it is used
func (m *RegisterConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterConfig) UnmarshalBinary(b []byte) error {
	var res RegisterConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
