// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RenewalOrderRequest RenewalOrderRequest
//
// swagger:model RenewalOrderRequest
type RenewalOrderRequest struct {

	// coupon
	Coupon string `json:"coupon,omitempty"`

	// payment
	// Required: true
	Payment *int64 `json:"payment"`

	// quantity
	// Required: true
	Quantity *int64 `json:"quantity"`

	// user subscribe id
	// Required: true
	UserSubscribeID *int64 `json:"user_subscribe_id"`
}

// Validate validates this renewal order request
func (m *RenewalOrderRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePayment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserSubscribeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RenewalOrderRequest) validatePayment(formats strfmt.Registry) error {

	if err := validate.Required("payment", "body", m.Payment); err != nil {
		return err
	}

	return nil
}

func (m *RenewalOrderRequest) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

func (m *RenewalOrderRequest) validateUserSubscribeID(formats strfmt.Registry) error {

	if err := validate.Required("user_subscribe_id", "body", m.UserSubscribeID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this renewal order request based on context it is used
func (m *RenewalOrderRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RenewalOrderRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RenewalOrderRequest) UnmarshalBinary(b []byte) error {
	var res RenewalOrderRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
