// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResetTrafficOrderRequest ResetTrafficOrderRequest
//
// swagger:model ResetTrafficOrderRequest
type ResetTrafficOrderRequest struct {

	// payment
	// Required: true
	Payment *int64 `json:"payment"`

	// user subscribe id
	// Required: true
	UserSubscribeID *int64 `json:"user_subscribe_id"`
}

// Validate validates this reset traffic order request
func (m *ResetTrafficOrderRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePayment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserSubscribeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResetTrafficOrderRequest) validatePayment(formats strfmt.Registry) error {

	if err := validate.Required("payment", "body", m.Payment); err != nil {
		return err
	}

	return nil
}

func (m *ResetTrafficOrderRequest) validateUserSubscribeID(formats strfmt.Registry) error {

	if err := validate.Required("user_subscribe_id", "body", m.UserSubscribeID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this reset traffic order request based on context it is used
func (m *ResetTrafficOrderRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResetTrafficOrderRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResetTrafficOrderRequest) UnmarshalBinary(b []byte) error {
	var res ResetTrafficOrderRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
