// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServerBasic ServerBasic
//
// swagger:model ServerBasic
type ServerBasic struct {

	// pull interval
	// Required: true
	PullInterval *int64 `json:"pull_interval"`

	// push interval
	// Required: true
	PushInterval *int64 `json:"push_interval"`
}

// Validate validates this server basic
func (m *ServerBasic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePullInterval(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePushInterval(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerBasic) validatePullInterval(formats strfmt.Registry) error {

	if err := validate.Required("pull_interval", "body", m.PullInterval); err != nil {
		return err
	}

	return nil
}

func (m *ServerBasic) validatePushInterval(formats strfmt.Registry) error {

	if err := validate.Required("push_interval", "body", m.PushInterval); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this server basic based on context it is used
func (m *ServerBasic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerBasic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerBasic) UnmarshalBinary(b []byte) error {
	var res ServerBasic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
