// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Shadowsocks Shadowsocks
//
// swagger:model Shadowsocks
type Shadowsocks struct {

	// method
	// Required: true
	Method *string `json:"method"`

	// port
	// Required: true
	Port *int32 `json:"port"`

	// server key
	// Required: true
	ServerKey *string `json:"server_key"`
}

// Validate validates this shadowsocks
func (m *Shadowsocks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServerKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Shadowsocks) validateMethod(formats strfmt.Registry) error {

	if err := validate.Required("method", "body", m.Method); err != nil {
		return err
	}

	return nil
}

func (m *Shadowsocks) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	return nil
}

func (m *Shadowsocks) validateServerKey(formats strfmt.Registry) error {

	if err := validate.Required("server_key", "body", m.ServerKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this shadowsocks based on context it is used
func (m *Shadowsocks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Shadowsocks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Shadowsocks) UnmarshalBinary(b []byte) error {
	var res Shadowsocks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
