// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StripePayment StripePayment
//
// swagger:model StripePayment
type StripePayment struct {

	// client secret
	// Required: true
	ClientSecret *string `json:"client_secret"`

	// method
	// Required: true
	Method *string `json:"method"`

	// publishable key
	// Required: true
	PublishableKey *string `json:"publishable_key"`
}

// Validate validates this stripe payment
func (m *StripePayment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientSecret(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublishableKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StripePayment) validateClientSecret(formats strfmt.Registry) error {

	if err := validate.Required("client_secret", "body", m.ClientSecret); err != nil {
		return err
	}

	return nil
}

func (m *StripePayment) validateMethod(formats strfmt.Registry) error {

	if err := validate.Required("method", "body", m.Method); err != nil {
		return err
	}

	return nil
}

func (m *StripePayment) validatePublishableKey(formats strfmt.Registry) error {

	if err := validate.Required("publishable_key", "body", m.PublishableKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this stripe payment based on context it is used
func (m *StripePayment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StripePayment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StripePayment) UnmarshalBinary(b []byte) error {
	var res StripePayment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
