// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubscribeType SubscribeType
//
// swagger:model SubscribeType
type SubscribeType struct {

	// subscribe types
	// Required: true
	SubscribeTypes []string `json:"subscribe_types"`
}

// Validate validates this subscribe type
func (m *SubscribeType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscribeTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubscribeType) validateSubscribeTypes(formats strfmt.Registry) error {

	if err := validate.Required("subscribe_types", "body", m.SubscribeTypes); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this subscribe type based on context it is used
func (m *SubscribeType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SubscribeType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscribeType) UnmarshalBinary(b []byte) error {
	var res SubscribeType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
