// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TimePeriod TimePeriod
//
// swagger:model TimePeriod
type TimePeriod struct {

	// end time
	// Required: true
	EndTime *string `json:"end_time"`

	// multiplier
	// Required: true
	Multiplier *float32 `json:"multiplier"`

	// start time
	// Required: true
	StartTime *string `json:"start_time"`
}

// Validate validates this time period
func (m *TimePeriod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMultiplier(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TimePeriod) validateEndTime(formats strfmt.Registry) error {

	if err := validate.Required("end_time", "body", m.EndTime); err != nil {
		return err
	}

	return nil
}

func (m *TimePeriod) validateMultiplier(formats strfmt.Registry) error {

	if err := validate.Required("multiplier", "body", m.Multiplier); err != nil {
		return err
	}

	return nil
}

func (m *TimePeriod) validateStartTime(formats strfmt.Registry) error {

	if err := validate.Required("start_time", "body", m.StartTime); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this time period based on context it is used
func (m *TimePeriod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TimePeriod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TimePeriod) UnmarshalBinary(b []byte) error {
	var res TimePeriod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
