// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Tuic Tuic
//
// swagger:model Tuic
type Tuic struct {

	// port
	// Required: true
	Port *int32 `json:"port"`

	// security config
	// Required: true
	SecurityConfig *SecurityConfig `json:"security_config"`
}

// Validate validates this tuic
func (m *Tuic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecurityConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tuic) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	return nil
}

func (m *Tuic) validateSecurityConfig(formats strfmt.Registry) error {

	if err := validate.Required("security_config", "body", m.SecurityConfig); err != nil {
		return err
	}

	if m.SecurityConfig != nil {
		if err := m.SecurityConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("security_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("security_config")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this tuic based on the context it is used
func (m *Tuic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSecurityConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tuic) contextValidateSecurityConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.SecurityConfig != nil {

		if err := m.SecurityConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("security_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("security_config")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Tuic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tuic) UnmarshalBinary(b []byte) error {
	var res Tuic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
