// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Vmess Vmess
//
// swagger:model Vmess
type Vmess struct {

	// port
	// Required: true
	Port *int32 `json:"port"`

	// security
	// Required: true
	Security *string `json:"security"`

	// security config
	// Required: true
	SecurityConfig *SecurityConfig `json:"security_config"`

	// transport
	// Required: true
	Transport *string `json:"transport"`

	// transport config
	// Required: true
	TransportConfig *TransportConfig `json:"transport_config"`
}

// Validate validates this vmess
func (m *Vmess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecurity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecurityConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransport(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransportConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Vmess) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	return nil
}

func (m *Vmess) validateSecurity(formats strfmt.Registry) error {

	if err := validate.Required("security", "body", m.Security); err != nil {
		return err
	}

	return nil
}

func (m *Vmess) validateSecurityConfig(formats strfmt.Registry) error {

	if err := validate.Required("security_config", "body", m.SecurityConfig); err != nil {
		return err
	}

	if m.SecurityConfig != nil {
		if err := m.SecurityConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("security_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("security_config")
			}
			return err
		}
	}

	return nil
}

func (m *Vmess) validateTransport(formats strfmt.Registry) error {

	if err := validate.Required("transport", "body", m.Transport); err != nil {
		return err
	}

	return nil
}

func (m *Vmess) validateTransportConfig(formats strfmt.Registry) error {

	if err := validate.Required("transport_config", "body", m.TransportConfig); err != nil {
		return err
	}

	if m.TransportConfig != nil {
		if err := m.TransportConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("transport_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("transport_config")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this vmess based on the context it is used
func (m *Vmess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSecurityConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTransportConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Vmess) contextValidateSecurityConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.SecurityConfig != nil {

		if err := m.SecurityConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("security_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("security_config")
			}
			return err
		}
	}

	return nil
}

func (m *Vmess) contextValidateTransportConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.TransportConfig != nil {

		if err := m.TransportConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("transport_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("transport_config")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Vmess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Vmess) UnmarshalBinary(b []byte) error {
	var res Vmess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
